issues:
  exclude-rules:
    - path: internal/http/interceptors/log/log.go
      text: "SA1019:"
      linters:
        - staticcheck
    - path: pkg/utils/utils.go
      text: "SA1019:"
      linters:
        - staticcheck
    - path: _test\.go
      linters:
        - exportloopref
linters-settings:
  govet:
    enable:
      - fieldalignment
linters:
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - depguard
    - revive
    - goimports
    - unconvert
    - exportloopref
    - misspell
    - gocritic
    - prealloc
    #- gosec
